## ============================================================
## auditmanager-default.properties
## Surcharge DataSource pour auditmanager uniquement
## kernel-default.properties reste inchangé
## ============================================================

spring.datasource.url=jdbc:postgresql://${mosip.kernel.database.hostname}:${mosip.kernel.database.port}/mosip_audit
spring.datasource.username=audituser
spring.datasource.password=${db.dbuser.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
