# Force kernel-auth-service (authmanager) à utiliser Postgres (mosip_kernel)
spring.datasource.url=${admin_database_url}
spring.datasource.username=${admin_database_username}
spring.datasource.password=${admin_database_password}

# S'assure que c'est bien Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel (mais utile) : évite toute init SQL automatique
spring.sql.init.mode=never
